// Generated by scripts/make-test-abr.ts: draws one stroke per control brush, saves control-sheet-N.png.
#target photoshop
var ROWS = [{"name":"C01 Size 10px","size":10,"band":140},{"name":"C02 Size 56px","size":56,"band":140},{"name":"C03 Size 100px","size":100,"band":155},{"name":"C04 Size 300px","size":300,"band":385},{"name":"C05 Size 1000px","size":1000,"band":1190},{"name":"C06 Hardness 0%","size":100,"band":155},{"name":"C07 Hardness 50%","size":100,"band":155},{"name":"C08 Hardness 100%","size":100,"band":155},{"name":"C09 Spacing 1%","size":100,"band":155},{"name":"C10 Spacing 25%","size":100,"band":155},{"name":"C11 Spacing 100%","size":100,"band":155},{"name":"C12 Spacing 200%","size":100,"band":155},{"name":"C13 Angle 0deg (arrow)","size":100,"band":155},{"name":"C14 Angle 45deg (arrow)","size":100,"band":155},{"name":"C15 Angle 90deg (arrow)","size":100,"band":155},{"name":"C16 Angle 180deg (arrow)","size":100,"band":155},{"name":"C17 Roundness 100%","size":100,"band":155},{"name":"C18 Roundness 50%","size":100,"band":155},{"name":"C19 Roundness 10%","size":100,"band":155},{"name":"C20 Roundness 0%","size":100,"band":155},{"name":"C21 Angle follows direction (arrow)","size":100,"band":155},{"name":"C22 Angle follows pen rotation (arrow)","size":100,"band":155},{"name":"C23 Size pressure min 0%","size":100,"band":155},{"name":"C24 Size pressure min 50%","size":100,"band":155},{"name":"C25 Opacity pressure","size":100,"band":155},{"name":"C26 Size jitter 50%","size":100,"band":155},{"name":"C27 Size jitter 100%","size":100,"band":155},{"name":"C28 Angle jitter 100% (arrow)","size":100,"band":155},{"name":"C29 Opacity jitter 50%","size":100,"band":155},{"name":"C30 Scatter 100%","size":50,"band":213},{"name":"C31 Scatter 300%","size":50,"band":442},{"name":"C32 Scatter 100% count 3","size":50,"band":213},{"name":"C33 Texture depth 25%","size":100,"band":155},{"name":"C34 Texture depth 100%","size":100,"band":155},{"name":"C35 Texture scale 50%","size":100,"band":155},{"name":"C36 Dual brush (dots)","size":100,"band":155}];
var W = 2400, MAX_H = 4000, LABEL = 36;
var dir = File($.fileName).parent;
app.preferences.rulerUnits = Units.PIXELS;
app.preferences.typeUnits = TypeUnits.PIXELS;

function selectBrush(name) {
    var r = new ActionReference(); r.putName(charIDToTypeID('Brsh'), name);
    var d = new ActionDescriptor(); d.putReference(charIDToTypeID('null'), r);
    executeAction(charIDToTypeID('slct'), d, DialogModes.NO);
}
function selectBrushTool() {
    var r = new ActionReference(); r.putClass(stringIDToTypeID('paintbrushTool'));
    var d = new ActionDescriptor(); d.putReference(charIDToTypeID('null'), r);
    executeAction(charIDToTypeID('slct'), d, DialogModes.NO);
}
function point(x, y, dx, dy) {
    var p = new PathPointInfo(); p.kind = PointKind.SMOOTHPOINT; p.anchor = [x, y];
    p.leftDirection = [x - dx, y - dy]; p.rightDirection = [x + dx, y + dy]; return p;
}
function stroke(doc, row, top) {
    var m = Math.max(80, row.size / 2 + 20), y = top + LABEL + row.band / 2, amp = Math.min(row.band / 4, 120), q = (W - 2 * m) / 4;
    var sp = new SubPathInfo(); sp.operation = ShapeOperation.SHAPEXOR; sp.closed = false;
    sp.entireSubPath = [point(m, y, q / 2, 0), point(m + q, y - amp, q / 2, 0), point(m + 3 * q, y + amp, q / 2, 0), point(W - m, y, q / 2, 0)];
    var path = doc.pathItems.add(row.name, [sp]);
    path.strokePath(ToolType.BRUSH, true); // simulated pressure: pressure brushes taper at both ends
    path.remove();
}
function label(doc, text, top) {
    var t = doc.artLayers.add(); t.kind = LayerKind.TEXT; t.name = text;
    t.textItem.contents = text; t.textItem.size = 24; t.textItem.position = [20, top + 28];
    var c = new SolidColor(); c.rgb.red = c.rgb.green = c.rgb.blue = 110; t.textItem.color = c;
}

var missing = [];
try { selectBrush(ROWS[0].name); } catch (e) { app.load(new File(dir + '/control.abr')); }
selectBrushTool();
var page = 0, i = 0;
while (i < ROWS.length) {
    var h = 0, j = i;
    while (j < ROWS.length && (j === i || h + LABEL + 2 * ROWS[j].band <= MAX_H)) { h += LABEL + 2 * ROWS[j].band; j++; }
    var doc = app.documents.add(W, h, 72, 'control-sheet-' + (++page), NewDocumentMode.RGB, DocumentFill.WHITE);
    var strokes = doc.artLayers.add(); strokes.name = 'Photoshop';
    var top = 0;
    for (var k = i; k < j; k++) {
        var row = ROWS[k];
        doc.activeLayer = strokes;
        try { selectBrush(row.name); stroke(doc, row, top); } catch (e) { missing.push(row.name); }
        label(doc, row.name + '  (Photoshop au-dessus, Infinite Painter en dessous)', top);
        top += LABEL + 2 * row.band;
    }
    var png = new PNGSaveOptions();
    doc.saveAs(new File(dir + '/control-sheet-' + page + '.png'), png, true, Extension.LOWERCASE);
    i = j;
}
alert(page + ' planche(s) enregistrée(s) dans ' + dir.fsName + (missing.length ? '\nPinceaux introuvables : ' + missing.join(', ') : ''));
